# Generated by Django 5.0.6 on 2024-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_person_age_person_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(choices=[('Работающий', 'Работающий'), ('Безработный', 'Безработный')], default='Работающий', max_length=20),
        ),
    ]
