# Generated by Django 5.0.6 on 2024-05-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(choices=[('Трудоустроенный', 'Трудоустроенный'), ('Безработный', 'Безработный')], default='Трудоустроенный', max_length=20),
        ),
    ]
