# Generated by Django 5.0.6 on 2024-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_person_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(choices=[('Трудоустроенный', 'Трудоустроенный'), ('Безработный', 'Безработный')], default='Безработный', max_length=250),
        ),
    ]
